In [2]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype.name

'int64'

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

In [9]:
b = np.array([1, 3, 4])
b

array([1, 3, 4])

In [10]:
type(b)

numpy.ndarray

#### Array creation

In [11]:
a = np.array([(2, 3, 4), (4, 5, 6)])
a

array([[2, 3, 4],
       [4, 5, 6]])

In [12]:
a.dtype

dtype('int64')

In [14]:
a.ndim

2

In [15]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [17]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [21]:
np.empty((2, 3))

array([[1.3574932e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

### Printing arrays

In [22]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [23]:
np.arange(24).reshape(6, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
np.arange(24).reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### basic operations

In [26]:
a = np.arange(4)
b = np.array([3, 4, 5, 6])

b

array([3, 4, 5, 6])

In [27]:
c = b - a

In [28]:
c

array([3, 3, 3, 3])

In [29]:
c ** 2

array([9, 9, 9, 9])

In [30]:
10 * np.sin(a)

array([0.        , 8.41470985, 9.09297427, 1.41120008])

In [31]:
## next
A = np.array([[1, 1], [0, 1]])

B = np.array([[2, 0], [3, 4]])

In [34]:
A * B

array([[2, 0],
       [0, 4]])

In [35]:
# Matrix product

In [36]:
A @ B

array([[5, 4],
       [3, 4]])

In [37]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [38]:
r = np.random.default_rng(1)

In [39]:
a = np.ones((2, 3), dtype=int)

In [41]:
b = r.random((2, 3))

In [44]:
a *= 3

In [45]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [46]:
a = np.ones(3, dtype=np.int32)

In [47]:
a

array([1, 1, 1], dtype=int32)

In [51]:
pi = 3.14
b = np.linspace(0, pi, 3)
b.dtype.name

'float64'

In [57]:
x = np.linspace(0, 10, 15)  # 14 elements from 0 to 15
x

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [62]:
y = r.random((3, 4))

In [63]:
y

array([[0.82770259, 0.40919914, 0.54959369, 0.02755911],
       [0.75351311, 0.53814331, 0.32973172, 0.7884287 ],
       [0.30319483, 0.45349789, 0.1340417 , 0.40311299]])

In [68]:
y.min()

0.027559113243068367

In [75]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [78]:
np.sum(b, axis=0)  # cumulative sum along the same column

array([12, 15, 18, 21])

In [79]:
np.sum(b, axis=1)  ## cumulative sum along the same row

array([ 6, 22, 38])

#### Universal functions

In [81]:
b = np.arange(3)

np.exp(b)

array([1.        , 2.71828183, 7.3890561 ])

In [82]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356])

In [84]:
c = np.array([4, 5, 6])
np.add(b, c)

array([4, 6, 8])

##### Indexing , slicing and iterating

In [88]:
a = np.arange(10) ** 2
a[2]

4

In [89]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [91]:
a[2:6]

array([ 4,  9, 16, 25])

In [92]:
a[:6:2] = 100

In [95]:
a[::-1]

array([ 81,  64,  49,  36,  25, 100,   9, 100,   1, 100])

In [97]:
b = np.arange(20).reshape(5, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [98]:
b[2, 3]

11

In [100]:
b[0:5, 1]

array([ 1,  5,  9, 13, 17])

In [102]:
b[:, 1]

array([ 1,  5,  9, 13, 17])

In [104]:
b[1:3, :]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
b[-1]

array([16, 17, 18, 19])

In [110]:
c = np.arange(24).reshape(2, 4, 3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [112]:
c.shape

(2, 4, 3)

In [114]:
c[
    1,
]

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [117]:
for i in c.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


#### shape Manipulation

In [120]:
a = np.floor(10 * r.random((3, 4)))
a

array([[5., 2., 8., 5.],
       [5., 7., 1., 8.],
       [6., 7., 1., 8.]])

In [122]:
a.shape

(3, 4)

In [124]:
## return the flatten array

a.ravel()

array([5., 2., 8., 5., 5., 7., 1., 8., 6., 7., 1., 8.])

In [125]:
a.reshape(6, 2)

array([[5., 2.],
       [8., 5.],
       [5., 7.],
       [1., 8.],
       [6., 7.],
       [1., 8.]])

In [128]:
a

array([[5., 2., 8., 5.],
       [5., 7., 1., 8.],
       [6., 7., 1., 8.]])

In [133]:
a.reshape(2, 6)

array([[5., 2., 8., 5., 5., 7.],
       [1., 8., 6., 7., 1., 8.]])

### Stacking together in a different arrays

In [135]:
a = np.floor(10 * r.random((2, 2)))
a

array([[8., 4.],
       [2., 0.]])

In [137]:
b = np.floor(10 * r.random((2, 2)))

In [139]:
b

array([[5., 0.],
       [6., 9.]])

In [141]:
np.vstack((a, b))

array([[8., 4.],
       [2., 0.],
       [5., 0.],
       [6., 9.]])

In [143]:
np.hstack((a, b))  ###

array([[8., 4., 5., 0.],
       [2., 0., 6., 9.]])

In [144]:
a = 5

In [146]:
id(a)

9788736

#### Copies and views

In [148]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [149]:
b = a

In [152]:
b is a
b

array([1, 2, 3])

In [156]:
id(a)

139878233329712

In [158]:
id(b)

139878233329712

In [159]:
time = np.linspace(20, 145, 5)

In [160]:
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [161]:
d = np.sin(np.arange(20)).reshape(5, 4)

In [163]:
d

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [169]:
d.argmax(axis=0)

array([2, 0, 3, 1])